### ISSUE TITLE
lara_cms.sql is incomplete

### ISSUE THREAD

**Issue by robernet** [kirilkirkov/Shopping-Cart-Solution-Laravel#1]
After loading lara_cms.sql file into the lara_cms database, an error showed about table products not having the tags fields. I added the tags fields as varchar(255), but the following error showed:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lara_cms.orders' doesn't exist (SQL: SELECT YEAR(FROM_UNIXTIME(UNIX_TIMESTAMP(time_created))) as year, MONTH(FROM_UNIXTIME(UNIX_TIMESTAMP(time_created))) as month, COUNT(id) as num FROM orders GROUP BY YEAR(FROM_UNIXTIME(UNIX_TIMESTAMP(time_created))), MONTH(FROM_UNIXTIME(UNIX_TIMESTAMP(time_created))) ASC )

So far I found that the orders table, as well as the carousel and carousel_translations are none existent.

**Comment by kirilkirkov** [comment]
Sorry. I forget to update database file.... It is fixed with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-Laravel/commit/a1073cd304cde60908ac270b6c8144a7d6120458  @robernet
