### ISSUE TITLE
Image carousel on public and admin Error (not showing)

### ISSUE THREAD

**Issue by s160414063** [kirilkirkov/Shopping-Cart-Solution-Laravel#4]
![1522315830225](https://user-images.githubusercontent.com/35355732/38081663-c4e4ed64-336e-11e8-8525-cc37589af044.jpg)
![1522315908065](https://user-images.githubusercontent.com/35355732/38081664-c51b15c4-336e-11e8-8050-f6c26248680b.jpg)
![1522315935417](https://user-images.githubusercontent.com/35355732/38081665-c55224d8-336e-11e8-80df-107f57686570.jpg)

**Comment by kirilkirkov** [comment]
Hello, @s160414063. Sorry for this bug. I fix it - https://github.com/kirilkirkov/Shopping-Cart-Solution-Laravel/commit/43334ebadd008903504ca7c40f5248481ba64d1b 
the reason was that the correct image for the selected language was not recorded
